language: cpp
dist: trusty
branches:
  only:
    - master

os:
  - linux

compiler:
  - clang
  - g++

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libsdl1.2-dev
      - libsdl-mixer1.2-dev
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libcurl4-openssl-dev
      - libbz2-dev
      - libminiupnpc-dev
      - liblua5.2-dev

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    - os: osx
     compiler: clang
     install:
       - brew update
       - brew install sdl
       - brew install sdl_mixer
       - brew install gettext
       - brew install miniupnpc
       - brew link --force gettext
     #                       Travis libs are x64 only
     env: BUILD_TYPE=Debug ADDITIONAL_CMAKE_FLAGS="-DRTTR_NOi386=ON"

before_install:
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  - mkdir -p ${DEPS_DIR}
  # Minimum requirements: CMake 3.8.2, Boost 1.64
  - |
    CMAKE_DIR="${DEPS_DIR}/cmake${TRAVIS_OS_NAME}"
    tools/ci/installCMake.sh "3.8.2" "${CMAKE_DIR}" cmakeSrc
    export PATH="${CMAKE_DIR}/bin:${PATH}"
  - |
    BOOST_VERSION=1.64.0
    BOOST_DIR="${DEPS_DIR}/boost${BOOST_VERSION}"
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      export DYLD_LIBRARY_PATH="${BOOST_DIR}/lib:${DYLD_LIBRARY_PATH}"
    else
      export LD_LIBRARY_PATH="${BOOST_DIR}/lib:${LD_LIBRARY_PATH}"
    fi
    export ADDITIONAL_CMAKE_FLAGS="${ADDITIONAL_CMAKE_FLAGS} -DBOOST_ROOT=${BOOST_DIR} -DBoost_NO_SYSTEM_PATHS=ON"
    tools/ci/installBoost.sh "${BOOST_VERSION}" "${BOOST_DIR}"

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-6"; export CC="gcc-6"; export GCOV="gcov-6"; fi
  # Enable coverage analysis only in debug and for g++
  - |
    if [ "$CXX" = "g++" ] && [ "$BUILD_TYPE" = "Debug" ]; then
      # Install newer lcov (1.9 seems to fail: http://gronlier.fr/blog/2015/01/adding-code-coverage-to-your-c-project/)
      export LCOV_ROOT="${DEPS_DIR}/lcov"
      LCOV_URL="http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz"
      mkdir "$LCOV_ROOT" && travis_retry wget --quiet -O - ${LCOV_URL} | tar --strip-components=1 -xz -C $LCOV_ROOT
      export PATH=${LCOV_ROOT}/bin:${PATH}
      which lcov

      # Install coveralls tool
      gem install coveralls-lcov

      # Enable
      export RTTR_COVERAGE="1"
      export ADDITIONAL_CMAKE_FLAGS="${ADDITIONAL_CMAKE_FLAGS} -DRTTR_ENABLE_COVERAGE=ON"
    else
      export RTTR_COVERAGE="0"
    fi

before_script:
  - "export DISPLAY=:99.0"
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )&
    else
      sh -e /etc/init.d/xvfb start
    fi
  - sleep 3 # give xvfb some time to start

script: tools/ci/travisBuild.sh

after_success:
  - |
    if [ "$RTTR_COVERAGE" = "1" ]; then
      tools/ci/uploadCoverageData.sh
    fi
