version: 0.8.3.{build}
branches:
  only:
  - master

image:
  - Visual Studio 2015
  - Visual Studio 2017

configuration:
  - Debug
  - Release

platform:
  - Win32
  - x64

environment:
  BOOST_ROOT: C:\Libraries\boost_1_60_0
  GENERATOR: Visual Studio 14 2015
  MSVC: 14.0
  RTTR_DISABLE_ASSERT_BREAKPOINT: 1

matrix:
  fast_finish: true
  exclude:
    - # Reduce build time, also VS2017,x64,Release Fails for some reason (Lua?)
      configuration: Release
      image: Visual Studio 2017

for:
  - matrix:
      only:
        - image: Visual Studio 2017
    environment:
      BOOST_ROOT: C:\Libraries\boost_1_67_0
      GENERATOR: Visual Studio 15 2017
      MSVC: 14.1

install:
  - dir C:\Libraries
  - appveyor-retry git submodule update --init
  - cd external
  - 7z x full-contrib-msvc.rar
  - cd ..

before_build:
  - if exist build\ (rmdir /S /Q build)
  - set INSTALL_DIR=%APPVEYOR_BUILD_FOLDER%\installed
  - if exist %INSTALL_DIR%\ (rmdir /S /Q %INSTALL_DIR%)
  - mkdir build
  - cd build
  - if %platform% == Win32 (set BOOST_LIBDIR=lib32-msvc-%MSVC%) else ((set BOOST_LIBDIR=lib64-msvc-%MSVC%) && (set GENERATOR=%GENERATOR% Win64))
  - echo "Configuring %GENERATOR% for %configuration% on %platform% with boost=%BOOST_ROOT%\%BOOST_LIBDIR%"
  - cmake -G "%GENERATOR%" -DRTTR_ENABLE_WERROR=ON -DCMAKE_INSTALL_PREFIX=%INSTALL_DIR% -DBOOST_LIBRARYDIR="%BOOST_ROOT%\%BOOST_LIBDIR%" ..

build:

build_script:
  - echo "Building for %configuration% on %platform%"
  - dir .
  - cmake --build . --target ALL_BUILD --config "%configuration%" --parallel
  - if %configuration% == Release (cmake --build . --target INSTALL --config "%configuration%" --parallel)

test_script:
  - ctest --output-on-failure -C %configuration%
