version: 0.8.3.{build}
branches:
  only:
  - master
  
os: Visual Studio 2015

configuration:
  - Debug
  - Release
  
platform:
  - Win32
  - x64

environment:
  matrix:
  - BOOST_ROOT: C:\Libraries\boost_1_59_0
    BOOST_LIBDIR_32: lib32-msvc-14.0
    BOOST_LIBDIR_64: lib64-msvc-14.0
    
install:
  - dir C:\Libraries
  - appveyor-retry git submodule update --init
  - cinst --allow-empty-checksums -y unrar
  - cd contrib
  - unrar x full-contrib-msvc.rar
  - cd ..

before_build:
  - cd build
  - if "%platform%"=="Win32" cmake -G "Visual Studio 14 2015" -DENABLE_WERROR=ON -DBOOST_LIBRARYDIR="%BOOST_ROOT%\%BOOST_LIBDIR_32%" ..
  - if "%platform%"=="x64" cmake -G "Visual Studio 14 2015 Win64" -DENABLE_WERROR=ON -DBOOST_LIBRARYDIR="%BOOST_ROOT%\%BOOST_LIBDIR_64%" ..
  - cd ..
    
build:

build_script:
  - echo "Building for %configuration% on %platform%"
  - msbuild /m /p:Configuration="%configuration%" /p:Platform="%platform%" /v:n build/s25client.sln

test_script:
  - cd build
  - set RTTR_DISABLE_ASSERT_BREAKPOINT="1"
  - echo "RTTR_DISABLE_ASSERT_BREAKPOINT=%RTTR_DISABLE_ASSERT_BREAKPOINT%"
  - ctest --output-on-failure -C %configuration%
  - cd ..
